### ISSUE TITLE
Input code seg fault on start-up (inconsistent)

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#106]
Reported by: ironstorm-gmail
Date: 2008-05-16T04:14:28Z
Status: Fix Released
Importance: Low
Launchpad Issue: [lp230939](https://bugs.launchpad.net/bugs/230939)

    Usually restarting Mixxx right after this crash works fine.

    Bombs out here:
    void Input::run()
    {
        while (1)
            getNextEvent();
    }

    Back trace below:
    .... 
    Debug: SoundManager::getDeviceList
    [New Thread 0x43851950 (LWP 24308)]
    Debug: PowerMate: write():  Bad file descriptor
    Debug: PowerMate: write():  Bad file descriptor
    Debug: HerculesLinux: Constructor called
    Debug: m_pHercules init:  QThread(0x1111600)
    Debug: Starting Hercules DJ Console detection
    No Hercules DJ Console found
    Debug: Sorry, no love.
    Debug: isRMX =  false
    [New Thread 0x44052950 (LWP 24309)]
    pure virtual method called
    terminate called without an active exception

    Program received signal SIGABRT, Aborted.
    [Switching to Thread 0x44052950 (LWP 24309)]
    0x00007f17da09f095 in raise () from /lib/libc.so.6
    (gdb) bt
    #0  0x00007f17da09f095 in raise () from /lib/libc.so.6
    #1  0x00007f17da0a0af0 in abort () from /lib/libc.so.6
    #2  0x00007f17da9240e4 in __gnu_cxx::__verbose_terminate_handler () from /usr/lib/libstdc++.so.6
    #3  0x00007f17da922076 in ?? () from /usr/lib/libstdc++.so.6
    #4  0x00007f17da9220a3 in std::terminate () from /usr/lib/libstdc++.so.6
    #5  0x00007f17da92275f in __cxa_pure_virtual () from /usr/lib/libstdc++.so.6
    #6  0x0000000000422a1a in Input::run (this=0x1111600) at src/input.cpp:58
    #7  0x00007f17dc6d6354 in ?? () from /usr/lib/libQtCore.so.4
    #8  0x00007f17db0443f7 in start_thread () from /lib/libpthread.so.0
    #9  0x00007f17da144b2d in clone () from /lib/libc.so.6
    #10 0x0000000000000000 in ?? ()

**Comment by Holzhaus** [comment]
Created by: gamegod
Date: 2008-05-20T16:16:51Z

    To clarify, the thing that kills it is the:
    "pure virtual method called"

    Why this happens is anybody's guess. Because it's intermittent, I'd guess that it's either an uninitialized variable somewhere or a race condition. (Is start() or run() called before some subclass is done initializing?)

**Comment by Holzhaus** [comment]
Created by: ironstorm-gmail
Date: 2008-05-24T20:29:27Z

    Hercules detect code was not exiting when a Hercules was not detected, this was causing Mixxx attempt to initalize the device + thread anyway...   That defect was corrected in r2015. 

    I think the correction will resolve this issue.

**Comment by Holzhaus** [comment]
Created by: gamegod
Date: 2008-05-31T14:10:23Z

    Tom got a bug report off an OS X user that sounds suspiciously like this me (beta3 and beta2). Tom reports that you also get this in the debugging output on OS X:
    Debug: m_pHercules init:  QObject(0x0)

    This may or may not be the same as this Hercules bug. The user reported that deleting his config file fixed the problem, so who knows. I'm not convinced that it was an invalid config file that broke Mixxx just by looking at the attached log.

**Comment by Holzhaus** [comment]
Created by: ironstorm-gmail
Date: 2008-05-31T14:37:15Z

    reopening...

**Comment by Holzhaus** [comment]
Created by: gamegod
Date: 2008-07-29T02:53:35Z

    Did we end up fixing this? I think RJ might have fixed this in the last two weeks...

**Comment by Holzhaus** [comment]
Created by: ironstorm-gmail
Date: 2009-03-31T23:24:23Z

    haven't seen this behaviour in ages, marking as fix released.

**Comment by Holzhaus** [comment]
Issue closed with status "Fix Released".
