### ISSUE TITLE
segfault after eject a track and move select recording feature

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#114]
This happens with mixxx 1.12.0-alpha-pre (build master r3530+)

Debug [Main]: PlaylistTableModel(0x19bc510) select() took 2 ms 
Debug []: Seeked to 2129920 Assumed: 2113536 

Program received signal SIGSEGV, Segmentation fault.
QMutex::lock (this=this@entry=0xd8) at thread/qmutex.cpp:150
150	thread/qmutex.cpp: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  QMutex::lock (this=this@entry=0xd8) at thread/qmutex.cpp:150
#1  0x00000000007daf35 in lockInline (this=0xd8)
    at /usr/include/qt4/QtCore/qmutex.h:198
#2  QMutexLocker (m=0xd8, this=0x7fffffffc040)
    at /usr/include/qt4/QtCore/qmutex.h:109
#3  TrackInfoObject::getLocation (this=0x0) at src/trackinfoobject.cpp:258
#4  0x0000000000815974 in PlayerInfo::isFileLoaded (this=<optimized out>, 
    track_location=...) at src/playerinfo.cpp:81
#5  0x00000000006b4498 in isTrackInUse (track_location=..., this=0x29370b8)
    at src/library/browse/browsetablemodel.cpp:298
#6  BrowseTableModel::flags (this=0x29370b8, index=...)
    at src/library/browse/browsetablemodel.cpp:286
#7  0x00007ffff6d3661b in QSortFilterProxyModel::flags (this=<optimized out>, 
    index=...) at itemviews/qsortfilterproxymodel.cpp:2003
#8  0x00007ffff6d0cd83 in flags (this=0x7fffffffc1c0)
    at ../../include/QtCore/../../src/corelib/kernel/qabstractitemmodel.h:405
#9  QItemSelectionModel::columnIntersectsSelection (this=<optimized out>, 
    column=column@entry=0, parent=...)
    at itemviews/qitemselectionmodel.cpp:1398
#10 0x00007ffff6ccdc4e in columnIntersectsSelection (column=0, this=0x29a6870)
    at ../../include/QtGui/private/../../../src/gui/itemviews/qheaderview_p.h:121
#11 sectionIntersectsSelection (logical=0, this=0x29a6870)
---Type <return> to continue, or q <return> to quit---
    at ../../include/QtGui/private/../../../src/gui/itemviews/qheaderview_p.h:125
#12 QHeaderView::paintSection (this=0x29394e0, painter=0x7fffffffc450, 
    rect=..., logicalIndex=0) at itemviews/qheaderview.cpp:2474
#13 0x00007ffff6ccc2aa in QHeaderView::paintEvent (this=0x29394e0, 
    e=<optimized out>) at itemviews/qheaderview.cpp:2125
#14 0x00007ffff67f7a3e in QWidget::event (this=this@entry=0x29394e0, 
    event=event@entry=0x7fffffffd0d0) at kernel/qwidget.cpp:8532
#15 0x00007ffff6baa316 in QFrame::event (this=0x29394e0, e=0x7fffffffd0d0)
    at widgets/qframe.cpp:557
#16 0x00007ffff6cc08bb in QAbstractItemView::viewportEvent (
    this=this@entry=0x29394e0, event=event@entry=0x7fffffffd0d0)
    at itemviews/qabstractitemview.cpp:1644
#17 0x00007ffff6cce59b in QHeaderView::viewportEvent (this=0x29394e0, 
    e=0x7fffffffd0d0) at itemviews/qheaderview.cpp:2445
#18 0x00007ffff74047a6 in QCoreApplicationPrivate::sendThroughObjectEventFilters (this=this@entry=0xe50e50, receiver=receiver@entry=0x29a7150, 
    event=event@entry=0x7fffffffd0d0) at kernel/qcoreapplication.cpp:1056
#19 0x00007ffff67aa8bc in QApplicationPrivate::notify_helper (
    this=this@entry=0xe50e50, receiver=receiver@entry=0x29a7150, 
    e=e@entry=0x7fffffffd0d0) at kernel/qapplication.cpp:4563
#20 0x00007ffff67ad25b in QApplication::notify (this=0x7fffffffdf70, 
    receiver=0x29a7150, e=0x7fffffffd0d0) at kernel/qapplication.cpp:4428
---Type <return> to continue, or q <return> to quit---
#21 0x00007ffff740463e in QCoreApplication::notifyInternal (this=
    0x7fffffffdf70, receiver=receiver@entry=0x29a7150, 
    event=event@entry=0x7fffffffd0d0) at kernel/qcoreapplication.cpp:946
#22 0x00007ffff67fc6b4 in sendSpontaneousEvent (event=0x7fffffffd0d0, 
    receiver=0x29a7150)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#23 QWidgetPrivate::drawWidget (this=this@entry=0x29a73b0, pdev=0x2408620, 
    rgn=..., offset=..., flags=flags@entry=68, 
    sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1e7be40) at kernel/qwidget.cpp:5598
#24 0x00007ffff69c1f5d in QWidgetBackingStore::sync (this=0x1e7be40)
    at painting/qbackingstore.cpp:1365
#25 0x00007ffff67eb060 in QWidgetPrivate::syncBackingStore (
    this=this@entry=0x10565b0) at kernel/qwidget.cpp:1896
#26 0x00007ffff67f7ee4 in QWidget::event (this=this@entry=0x1058340, 
    event=event@entry=0x2485890) at kernel/qwidget.cpp:8679
#27 0x00007ffff6bc383b in QMainWindow::event (this=0x1058340, event=0x2485890)
    at widgets/qmainwindow.cpp:1478
#28 0x00007ffff67aa8ec in QApplicationPrivate::notify_helper (
    this=this@entry=0xe50e50, receiver=receiver@entry=0x1058340, 
    e=e@entry=0x2485890) at kernel/qapplication.cpp:4567
#29 0x00007ffff67ad25b in QApplication::notify (this=0x7fffffffdf70, 
    receiver=0x1058340, e=0x2485890) at kernel/qapplication.cpp:4428
---Type <return> to continue, or q <return> to quit---
#30 0x00007ffff740463e in QCoreApplication::notifyInternal (
    this=0x7fffffffdf70, receiver=receiver@entry=0x1058340, 
    event=event@entry=0x2485890) at kernel/qcoreapplication.cpp:946
#31 0x00007ffff7408171 in sendEvent (event=0x2485890, receiver=0x1058340)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#32 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, 
    event_type=event_type@entry=0, data=0xde95a0)
    at kernel/qcoreapplication.cpp:1570
#33 0x00007ffff74084a3 in QCoreApplication::sendPostedEvents (
    receiver=receiver@entry=0x0, event_type=event_type@entry=0)
    at kernel/qcoreapplication.cpp:1463
#34 0x00007ffff7432e83 in sendPostedEvents ()
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:236
#35 postEventSourceDispatch (s=0xe52230)
    at kernel/qeventdispatcher_glib.cpp:279
#36 0x00007ffff05c7f05 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff05c8248 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff05c8304 in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007ffff7433016 in QEventDispatcherGlib::processEvents (this=0xe51f90, 
    flags=...) at kernel/qeventdispatcher_glib.cpp:424
#40 0x00007ffff68501ae in QGuiEventDispatcherGlib::processEvents (
---Type <return> to continue, or q <return> to quit---
    this=<optimized out>, flags=...) at kernel/qguieventdispatcher_glib.cpp:204
#41 0x00007ffff740338f in QEventLoop::processEvents (this=this@entry=
    0x7fffffffde50, flags=...) at kernel/qeventloop.cpp:149
#42 0x00007ffff7403618 in QEventLoop::exec (this=this@entry=0x7fffffffde50, 
    flags=...) at kernel/qeventloop.cpp:204
#43 0x00007ffff7408cf6 in QCoreApplication::exec ()
    at kernel/qcoreapplication.cpp:1218
#44 0x00007ffff67a8ffc in QApplication::exec () at kernel/qapplication.cpp:3828
#45 0x0000000000441acd in main (argc=1, argv=<optimized out>)
    at src/main.cpp:316
(gdb)

**Comment by Holzhaus** [comment]
(by daschuer)
Fixed in 1.12.0-alpha-pre (build master r3533) 
commit 3741d682a0ef44a4bf223b49df507e50e2df5f8f
