### ISSUE TITLE
Crash on exit with two mono channels from the same device configured

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#121]
I set master to be channel 1 (mono) and headphones to be channel 2 (mono) of the same device.  On exit I get a crash, likely due to double-closing of the device I'm guessing:

Debug [Main]: Destroying MixxxApp 
Debug [Main]: save config  0 
Debug [Main]: delete soundmanager  1 

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff830a4700 (LWP 7334)]
0x00000000008f7467 in SoundManager::requestBuffer (this=0x11b6d20, outputs=..., outputBuffer=outputBuffer@entry=0x241f5c0, iFramesPerBuffer=iFramesPerBuffer@entry=1024, 
    iFrameSize=iFrameSize@entry=2, device=device@entry=0x11b93b0) at src/soundmanager.cpp:495
495	                                       pAudioOutputBuffer[i*2 + 1]) / 2.0f;
(gdb) thread apply all bt

Thread 33 (Thread 0x7fff830a4700 (LWP 7334)):
#0  0x00000000008f7467 in SoundManager::requestBuffer (this=0x11b6d20, outputs=..., outputBuffer=outputBuffer@entry=0x241f5c0, 
    iFramesPerBuffer=iFramesPerBuffer@entry=1024, iFrameSize=iFrameSize@entry=2, device=device@entry=0x11b93b0) at src/soundmanager.cpp:495
#1  0x00000000008f246d in SoundDevicePortAudio::callbackProcess (this=0x11b93b0, framesPerBuffer=1024, output=0x241f5c0, in=<optimized out>, timeInfo=<optimized out>, 
    statusFlags=<optimized out>) at src/sounddeviceportaudio.cpp:331
#2  0x00007ffff7bb4053 in ?? () from /usr/lib/x86_64-linux-gnu/libportaudio.so.2
#3  0x00007ffff7bb6045 in ?? () from /usr/lib/x86_64-linux-gnu/libportaudio.so.2
#4  0x00007ffff7bbcf68 in ?? () from /usr/lib/x86_64-linux-gnu/libportaudio.so.2
#5  0x00007ffff32b1f6e in start_thread (arg=0x7fff830a4700) at pthread_create.c:311
#6  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 32 (Thread 0x7ffef1b3f700 (LWP 7188)):
#0  0x00007ffff1e20f7d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff064e6a4 in g_main_context_poll (priority=2147483647, n_fds=2, fds=0x7ffee8002bb0, timeout=-1, context=0x7ffee80009a0)
    at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:4006
#2  g_main_context_iterate (context=context@entry=0x7ffee80009a0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:3707
#3  0x00007ffff064e7ac in g_main_context_iteration (context=0x7ffee80009a0, may_block=1) at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:3773
#4  0x00007ffff57eea76 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff57c05ef in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#6  0x00007ffff57c08e5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007ffff56bf88f in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007ffff57a1d13 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#9  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#10 0x00007ffff32b1f6e in start_thread (arg=0x7ffef1b3f700) at pthread_create.c:311
#11 0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 31 (Thread 0x7ffef238f700 (LWP 7187)):
#0  0x00007ffff1e20f7d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff064e6a4 in g_main_context_poll (priority=2147483647, n_fds=2, fds=0x7ffee4002ac0, timeout=-1, context=0x7ffee40009a0)
    at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:4006
#2  g_main_context_iterate (context=context@entry=0x7ffee40009a0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:3707
#3  0x00007ffff064e7ac in g_main_context_iteration (context=0x7ffee40009a0, may_block=1) at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:3773
#4  0x00007ffff57eea76 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff57c05ef in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#6  0x00007ffff57c08e5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007ffff56bf88f in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007ffff57a1d13 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#9  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#10 0x00007ffff32b1f6e in start_thread (arg=0x7ffef238f700) at pthread_create.c:311
#11 0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
---Type <return> to continue, or q <return> to quit---

Thread 29 (Thread 0x7fff81462700 (LWP 7185)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff5ff606b in ?? () from /usr/lib/x86_64-linux-gnu/libQtScript.so.4
#2  0x00007ffff5ff60a9 in ?? () from /usr/lib/x86_64-linux-gnu/libQtScript.so.4
#3  0x00007ffff32b1f6e in start_thread (arg=0x7fff81462700) at pthread_create.c:311
#4  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 28 (Thread 0x7fff81c63700 (LWP 7183)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff56be5eb in QSemaphore::acquire(int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00000000004cc6c8 in CachingReaderWorker::run (this=0x580db50) at src/cachingreaderworker.cpp:124
#4  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff32b1f6e in start_thread (arg=0x7fff81c63700) at pthread_create.c:311
#6  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 27 (Thread 0x7fff82464700 (LWP 7182)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff56be5eb in QSemaphore::acquire(int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00000000004cc6c8 in CachingReaderWorker::run (this=0x4492190) at src/cachingreaderworker.cpp:124
#4  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff32b1f6e in start_thread (arg=0x7fff82464700) at pthread_create.c:311
#6  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 25 (Thread 0x7fff8bfff700 (LWP 7171)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff56be5eb in QSemaphore::acquire(int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x000000000098d58d in VSyncThread::run (this=0x2232bf0) at src/waveform/vsyncthread.cpp:77
#4  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff32b1f6e in start_thread (arg=0x7fff8bfff700) at pthread_create.c:311
#6  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 24 (Thread 0x7fff99797700 (LWP 7170)):
#0  0x00007ffff1e20f7d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff064e6a4 in g_main_context_poll (priority=2147483647, n_fds=1, fds=0x7fffd4003780, timeout=4, context=0x7fffd4003450)
    at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:4006
#2  g_main_context_iterate (context=context@entry=0x7fffd4003450, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:3707
#3  0x00007ffff064e7ac in g_main_context_iteration (context=0x7fffd4003450, may_block=1) at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:3773
#4  0x00007ffff57eea55 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
---Type <return> to continue, or q <return> to quit---
#5  0x00007ffff57c05ef in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#6  0x00007ffff57c08e5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007ffff56bf88f in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#9  0x00007ffff32b1f6e in start_thread (arg=0x7fff99797700) at pthread_create.c:311
#10 0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 23 (Thread 0x7fffde1d0700 (LWP 7169)):
#0  0x00007ffff1e20f7d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff34d5198 in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#2  0x00007ffff32b1f6e in start_thread (arg=0x7fffde1d0700) at pthread_create.c:311
#3  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 22 (Thread 0x7fff99f98700 (LWP 7167)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00000000004afe59 in AnalyserQueue::dequeueNextBlocking (this=this@entry=0x21c7560) at src/analyserqueue.cpp:118
#3  0x00000000004b228e in AnalyserQueue::run (this=0x21c7560) at src/analyserqueue.cpp:279
#4  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff32b1f6e in start_thread (arg=0x7fff99f98700) at pthread_create.c:311
#6  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 21 (Thread 0x7fff9a799700 (LWP 7166)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x0000000000779e5a in BrowseThread::run (this=0x1175ee0) at src/library/browse/browsethread.cpp:82
#3  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff32b1f6e in start_thread (arg=0x7fff9a799700) at pthread_create.c:311
#5  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 20 (Thread 0x7fff9ba61700 (LWP 7165)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff56be5eb in QSemaphore::acquire(int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00000000004cc6c8 in CachingReaderWorker::run (this=0x1f73ef0) at src/cachingreaderworker.cpp:124
#4  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff32b1f6e in start_thread (arg=0x7fff9ba61700) at pthread_create.c:311
#6  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 19 (Thread 0x7fffad32e700 (LWP 7164)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff56be5eb in QSemaphore::acquire(int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
---Type <return> to continue, or q <return> to quit---
#3  0x00000000004cc6c8 in CachingReaderWorker::run (this=0x1d566a0) at src/cachingreaderworker.cpp:124
#4  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff32b1f6e in start_thread (arg=0x7fffad32e700) at pthread_create.c:311
#6  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 18 (Thread 0x7fffaebbc700 (LWP 7162)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff56be5eb in QSemaphore::acquire(int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00000000004cc6c8 in CachingReaderWorker::run (this=0x1b41040) at src/cachingreaderworker.cpp:124
#4  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff32b1f6e in start_thread (arg=0x7fffaebbc700) at pthread_create.c:311
#6  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 17 (Thread 0x7fffaffff700 (LWP 7161)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff56be5eb in QSemaphore::acquire(int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00000000004cc6c8 in CachingReaderWorker::run (this=0x192ba00) at src/cachingreaderworker.cpp:124
#4  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff32b1f6e in start_thread (arg=0x7fffaffff700) at pthread_create.c:311
#6  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 16 (Thread 0x7fffbdceb700 (LWP 7160)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff56be5eb in QSemaphore::acquire(int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00000000004cc6c8 in CachingReaderWorker::run (this=0x1712360) at src/cachingreaderworker.cpp:124
#4  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff32b1f6e in start_thread (arg=0x7fffbdceb700) at pthread_create.c:311
#6  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 15 (Thread 0x7fffbf579700 (LWP 7159)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff56be5eb in QSemaphore::acquire(int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00000000004cc6c8 in CachingReaderWorker::run (this=0x1504320) at src/cachingreaderworker.cpp:124
#4  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff32b1f6e in start_thread (arg=0x7fffbf579700) at pthread_create.c:311
#6  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 14 (Thread 0x7fffc4e46700 (LWP 7158)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
---Type <return> to continue, or q <return> to quit---
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff56be5eb in QSemaphore::acquire(int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00000000004cc6c8 in CachingReaderWorker::run (this=0x12990b0) at src/cachingreaderworker.cpp:124
#4  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff32b1f6e in start_thread (arg=0x7fffc4e46700) at pthread_create.c:311
#6  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 13 (Thread 0x7fffc6b1a700 (LWP 7157)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x000000000096c7c1 in VinylControlProcessor::run (this=0x124e5e0) at src/vinylcontrol/vinylcontrolprocessor.cpp:130
#3  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff32b1f6e in start_thread (arg=0x7fffc6b1a700) at pthread_create.c:311
#5  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 7 (Thread 0x7fffc7fff700 (LWP 7149)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x000000000070e67f in EngineSideChain::run (this=0x11a1af0) at src/engine/sidechain/enginesidechain.cpp:93
#3  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff32b1f6e in start_thread (arg=0x7fffc7fff700) at pthread_create.c:311
#5  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 6 (Thread 0x7fffdd1ce700 (LWP 7148)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff56c2406 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00000000006f23b6 in EngineWorkerScheduler::run (this=0x115c220) at src/engine/engineworkerscheduler.cpp:43
#3  0x00007ffff56c1f2f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff32b1f6e in start_thread (arg=0x7fffdd1ce700) at pthread_create.c:311
#5  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 5 (Thread 0x7fffdd9cf700 (LWP 7146)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x00007ffff068e705 in g_cond_wait_until (cond=cond@entry=0x10e2308, mutex=mutex@entry=0x10e2300, end_time=end_time@entry=345294902078)
    at /build/buildd/glib2.0-2.38.1/./glib/gthread-posix.c:876
#2  0x00007ffff0624c51 in g_async_queue_pop_intern_unlocked (queue=queue@entry=0x10e2300, wait=wait@entry=1, end_time=end_time@entry=345294902078)
    at /build/buildd/glib2.0-2.38.1/./glib/gasyncqueue.c:424
#3  0x00007ffff06251db in g_async_queue_timeout_pop (queue=0x10e2300, timeout=timeout@entry=15000000) at /build/buildd/glib2.0-2.38.1/./glib/gasyncqueue.c:545
#4  0x00007ffff0673b86 in g_thread_pool_wait_for_new_pool () at /build/buildd/glib2.0-2.38.1/./glib/gthreadpool.c:169
#5  g_thread_pool_thread_proxy (data=<optimized out>) at /build/buildd/glib2.0-2.38.1/./glib/gthreadpool.c:366
#6  0x00007ffff06730f5 in g_thread_proxy (data=0x1047e80) at /build/buildd/glib2.0-2.38.1/./glib/gthread.c:798
#7  0x00007ffff32b1f6e in start_thread (arg=0x7fffdd9cf700) at pthread_create.c:311
#8  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
---Type <return> to continue, or q <return> to quit---

Thread 3 (Thread 0x7fffde9d1700 (LWP 7144)):
#0  0x00007ffff1e20f7d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff064e6a4 in g_main_context_poll (priority=2147483647, n_fds=2, fds=0x7fffd00008c0, timeout=-1, context=0x10e14f0)
    at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:4006
#2  g_main_context_iterate (context=context@entry=0x10e14f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:3707
#3  0x00007ffff064e7ac in g_main_context_iteration (context=0x10e14f0, may_block=may_block@entry=1) at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:3773
#4  0x00007ffff064e7f9 in glib_worker_main (data=<optimized out>) at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:5472
#5  0x00007ffff06730f5 in g_thread_proxy (data=0x1047ed0) at /build/buildd/glib2.0-2.38.1/./glib/gthread.c:798
#6  0x00007ffff32b1f6e in start_thread (arg=0x7fffde9d1700) at pthread_create.c:311
#7  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 2 (Thread 0x7fffdff08700 (LWP 7143)):
#0  0x00007ffff1e20f7d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff064e6a4 in g_main_context_poll (priority=2147483647, n_fds=5, fds=0x7fffd8009a90, timeout=-1, context=0x1070000)
    at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:4006
#2  g_main_context_iterate (context=0x1070000, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:3707
#3  0x00007ffff064eb0a in g_main_loop_run (loop=0x1066870) at /build/buildd/glib2.0-2.38.1/./glib/gmain.c:3906
#4  0x00007fffe78d3b66 in gdbus_shared_thread_func (user_data=0x106ffd0) at /build/buildd/glib2.0-2.38.1/./gio/gdbusprivate.c:278
#5  0x00007ffff06730f5 in g_thread_proxy (data=0x1047cf0) at /build/buildd/glib2.0-2.38.1/./glib/gthread.c:798
#6  0x00007ffff32b1f6e in start_thread (arg=0x7fffdff08700) at pthread_create.c:311
#7  0x00007ffff1e2d9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 1 (Thread 0x7ffff7f967c0 (LWP 7103)):
#0  0x00007ffff32b31f8 in pthread_join (threadid=140735391876864, thread_return=0x7fffffffd788) at pthread_join.c:92
#1  0x00007ffff7bc65ad in ?? () from /usr/lib/x86_64-linux-gnu/libportaudio.so.2
#2  0x00007ffff7bba863 in ?? () from /usr/lib/x86_64-linux-gnu/libportaudio.so.2
#3  0x00000000008f2be5 in SoundDevicePortAudio::close (this=0x11b93b0) at src/sounddeviceportaudio.cpp:246
#4  0x00000000008f8d36 in SoundManager::closeDevices (this=this@entry=0x11b6d20) at src/soundmanager.cpp:137
#5  0x00000000008f9be0 in SoundManager::clearDeviceList (this=this@entry=0x11b6d20) at src/soundmanager.cpp:169
#6  0x00000000008f9d84 in SoundManager::~SoundManager (this=0x11b6d20, __in_chrg=<optimized out>) at src/soundmanager.cpp:75
#7  0x00000000008f9f49 in SoundManager::~SoundManager (this=0x11b6d20, __in_chrg=<optimized out>) at src/soundmanager.cpp:88
#8  0x0000000000873fd4 in MixxxApp::~MixxxApp (this=0x11593b0, __in_chrg=<optimized out>) at src/mixxx.cpp:580
#9  0x00000000008752a9 in MixxxApp::~MixxxApp (this=0x11593b0, __in_chrg=<optimized out>) at src/mixxx.cpp:680
#10 0x000000000046f9ae in main (argc=4, argv=<optimized out>) at src/main.cpp:346
(gdb) 
(gdb)

**Comment by Holzhaus** [comment]
(by rryan)
This was caused by freeing the downmix buffer before all the devices were closed. Fixed in 
https://github.com/mixxxdj/mixxx/commit/88490db158dcac0dc72aaff0256026b0b84cf27b
