### ISSUE TITLE
DlgPrefEq segfault while setting up EQ selectors

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#148]
Here is the backtrace :

0  QLabel::setText (this=0x70006f006f006c, text=...) at widgets/qlabel.cpp:353
#1  0x00000000005f736c in DlgPrefEQ::slotSingleEqChecked (this=this@entry=0x2eeb960, checked=<optimized out>)
    at src/dlgprefeq.cpp:279
#2  0x00000000005f7849 in DlgPrefEQ::loadSettings (this=this@entry=0x2eeb960) at src/dlgprefeq.cpp:301
#3  0x00000000005fd322 in DlgPrefEQ::DlgPrefEQ (this=0x2eeb960, pParent=<optimized out>, pEffectsManager=<optimized out>, 
    pConfig=<optimized out>) at src/dlgprefeq.cpp:82
#4  0x0000000000604b2e in DlgPreferences::DlgPreferences (this=0x2e653f0, mixxx=<optimized out>, pSkinLoader=0x2d8f8d0, soundman=
    0x1f30320, pPlayerManager=<optimized out>, controllers=0x2da5020, pVCManager=0x206ae70, pEffectsManager=0x13dc9e0, 
    pConfig=0x1349770, pLibrary=0x2b45b50) at src/dlgpreferences.cpp:104
#5  0x00000000009ca20d in MixxxMainWindow::MixxxMainWindow (this=0x13475d0, pApp=0x7fffffffdf60, args=...) at src/mixxx.cpp:338
#6  0x0000000000480631 in main (argc=4, argv=<optimized out>) at src/main.cpp:338

This error occured after a friend of mine tried to launch Mixxx 1.11 (I don't use it for a while).
Mixxx then stopped to start.

To be able to play musique I had to set a custom settingsPath.

**Comment by Holzhaus** [comment]
(by rryan)
Added a band-aid in to prevent the segfault though I don't see how this happened. The code in DlgPrefEq could use a rewrite.

 https://github.com/mixxxdj/mixxx/commit/e0d070e7d5d6309cd3f2c143db35ee753cb0260b

**Comment by Holzhaus** [comment]
(by rryan)
Jean -- do you still have the old profile that caused this? 

Could you paste the mixxx.cfg and verify that it doesn't segfault with the fix in master?

**Comment by Holzhaus** [comment]
(by jean-claveau-g)
Here is my config.

And averything works with the last fix, thanks! :)
