### ISSUE TITLE
crash returning from fullscreen

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#172]
This is new in 1.12.  Use F11 to go fullscreen, and then press again.  Crash.  Probably happened in LaunchImage changes

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5ec9c1c in QWidget::insertAction(QAction*, QAction*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
(gdb) bt
#0  0x00007ffff5ec9c1c in QWidget::insertAction(QAction*, QAction*) () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#1  0x000000000084d477 in MixxxMainWindow::initMenuBar() (this=0x1243fb0) at src/mixxx.cpp:1641
#2  0x000000000084e9cc in MixxxMainWindow::slotViewFullScreen(bool) (this=0x1243fb0, toggle=false) at src/mixxx.cpp:1880
#3  0x0000000000864615 in MixxxMainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x1243fb0, _c=QMetaObject::InvokeMetaMethod, _id=31, _a=0x7fffffffca30) at lin64_build/moc_mixxx.cc:168
#4  0x00007ffff549a1ec in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff5e76052 in QAction::toggled(bool) () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#6  0x00007ffff5e77a6f in QAction::setChecked(bool) () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#7  0x00007ffff5e77bb4 in QAction::activate(QAction::ActionEvent) () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#8  0x00007ffff5e780cc in QAction::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#9  0x00007ffff5e7c9bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#10 0x00007ffff5e834d8 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#11 0x0000000000854129 in MixxxApplication::notify(QObject*, QEvent*) (this=0x7fffffffdd30, target=0x3721e00, event=0x7fffffffce80)
    at src/mixxxapplication.cpp:138
#12 0x00007ffff54851cd in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#13 0x00007ffff5eb06ab in  () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#14 0x00007ffff5eb0814 in  () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#15 0x00007ffff5e84956 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#16 0x0000000000854129 in MixxxApplication::notify(QObject*, QEvent*) (this=0x7fffffffdd30, target=0x1243fb0, event=0x7fffffffd2c0)
    at src/mixxxapplication.cpp:138
#17 0x00007ffff54851cd in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#18 0x00007ffff5f22023 in  () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#19 0x00007ffff5f224c2 in  () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#20 0x00007ffff5efb316 in QApplication::x11ProcessEvent(_XEvent*) () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#21 0x00007ffff5f24ba2 in  () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#22 0x00007ffff0151c3d in g_main_context_dispatch (context=0x1000880) at /build/buildd/glib2.0-2.44.1/./glib/gmain.c:3122
#23 0x00007ffff0151c3d in g_main_context_dispatch (context=context@entry=0x1000880) at /build/buildd/glib2.0-2.44.1/./glib/gmain.c:3737
#24 0x00007ffff0151f20 in g_main_context_iterate (context=context@entry=0x1000880, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.44.1/./glib/gmain.c:3808
#25 0x00007ffff0151fcc in g_main_context_iteration (context=0x1000880, may_block=1) at /build/buildd/glib2.0-2.44.1/./glib/gmain.c:3869
#26 0x00007ffff54b487e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#27 0x00007ffff5f24c66 in  () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#28 0x00007ffff5483d21 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#29 0x00007ffff5484085 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#30 0x00007ffff5489b09 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#31 0x000000000083ddb8 in main(int, char**) (argc=1, argv=0x7fffffffde68) at src/main.cpp:315
(gdb)

**Comment by Holzhaus** [comment]
(by ywwg)
Bad commit is this one: https://github.com/mixxxdj/mixxx/commit/5a657cb0036e1fc83df484a10dc466dc56459b71

**Comment by Holzhaus** [comment]
(by daschuer)
Should be fixed in latest 1.12 https://github.com/mixxxdj/mixxx/commit/22c5018ff50d189c9abfbfa1d00b1805785ca0e6
Please verify it with a native Menu bar desktop like Ubuntu Unit, Thank you.

**Comment by Holzhaus** [comment]
(by ywwg)
Fix verified.  Works on Ubuntu with menu bar either in window or on top-level bar.  Thanks for the fast fix!
