### ISSUE TITLE
Crashes on loading MP3

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#175]
Reported by: lanquarden
Date: 2008-09-29T16:01:14Z
Status: Invalid
Importance: Undecided
Launchpad Issue: [lp275944](https://bugs.launchpad.net/bugs/275944)
Tags: jack, realtime

    Everytime I try to load an MP3 mixxx crashes providing following output:

        Debug: Load to player1: "/home/lq/Music/2006 - electric gypsyland 2/A15) - ismail oro (43 skidoo_susheela raman remix) (feat. susheela raman vs kocani orkestar).mp3"
        Debug: SSMP3::ParseHeader - frames read:  11  bitrate  320
        Debug: SSMP3::ParseHeader - samplerate  44100  channels  2
        Debug: SSMP3::ParseHeader - CBR bytes per frame 1044  Estimated duration  338
        terminate called after throwing an instance of 'std::bad_alloc'
          what():  std::bad_alloc
        Aborted

    If I change the waveform display to simple it loads the MP3 fine, but of course there's no waveform, the output:

        Debug: Load to player1: "/home/lq/Music/2006 - electric gypsyland 2/A15) - ismail oro (43 skidoo_susheela raman remix) (feat. susheela raman vs kocani orkestar).mp3"
        Debug: SSMP3::ParseHeader - frames read:  11  bitrate  320
        Debug: SSMP3::ParseHeader - samplerate  44100  channels  2
        Debug: SSMP3::ParseHeader - CBR bytes per frame 1044  Estimated duration  338
        Debug: WaveformRenderBeat :: BPM =  90.0235
        Debug: SSMP3() :: Setting SRATE to  44100  from  0
        Debug: SSMP3() :: Setting SRATE to  44100  from  0
        Debug: file length  29698560 i
        Debug: WaveformRenderBeat :: samples =  29698560
        Debug: WaveformRenderMark :: samples =  29698560
        Debug: WaveformRenderMark :: MarkPoint =  0
        Debug: WaveSummary: f  44100  samplesPerDownsample:  110  downsamples  269986  from  29698560
        Debug: WaveSummary :: Beginning to downsample waveform.
        Debug: WaveSummary :: Waveform downsampling finished.
        Debug: WaveSummary :: Generation took  5.49  seconds

    It crashes on every MP3 I tried up until now, seems to be fine with FLAC files.

    Currently using 1.6.1 (ubuntu) version, had the same with 1.6.0 (ubuntu) version and 1.6.0-beta2 which comes with Ubuntu Studio 8.04 although with the last I experienced only crashes when changing a song.

**Comment by Holzhaus** [comment]
Created by: gamegod
Date: 2008-09-30T00:00:38Z

    Hi lanquarden, 

    Can you please generate a backtrace for us when Mixxx crashes? Instructions are available here:
    http://www.mixxx.org/wiki/doku.php/creating_backtraces

    This will help us track down the crash.

    How much RAM do you have?
    What kind of videocard do you have?

    Thanks,
    Albert

**Comment by Holzhaus** [comment]
Created by: lanquarden
Date: 2008-09-30T12:29:33Z

    Output free -m when mixxx loaded:
                 total       used       free     shared    buffers     cached
    Mem:           972        664        307          0         13        266
    -/+ buffers/cache:        384        588
    Swap:          956          0        956

    Output lspci | grep VGA:
    00:02.0 VGA compatible controller: Intel Corporation 82852/855GM Integrated Graphics Device (rev 02)

    Backtrace with gdb:
    Debug: Load to player1: "/home/lq/Music/2006 - electric gypsyland 2/A15) - ismail oro (43 skidoo_susheela raman remix) (feat. susheela raman vs kocani orkestar).mp3" 
    Debug: SSMP3::ParseHeader - frames read:  11  bitrate  320 
    Debug: SSMP3::ParseHeader - samplerate  44100  channels  2 
    Debug: SSMP3::ParseHeader - CBR bytes per frame 1044  Estimated duration  338 
    terminate called after throwing an instance of 'std::bad_alloc'
      what():  std::bad_alloc

    Program received signal SIGABRT, Aborted.
    [Switching to Thread 0xaf2e5b90 (LWP 5697)]
    0xb7ee8410 in __kernel_vsyscall ()
    (gdb) thread apply all bt

    Thread 12 (Thread 0xac145b90 (LWP 5702)):
    #0  0xb7ee8410 in __kernel_vsyscall ()
    #1  0xb6fc6aa5 in pthread_cond_wait@@GLIBC_2.3.2 ()
       from /lib/tls/i686/cmov/libpthread.so.0
    #2  0xb720c924 in QWaitCondition::wait () from /usr/lib/libQtCore.so.4
    #3  0x0820eb3e in ?? ()
    #4  0xb720c057 in ?? () from /usr/lib/libQtCore.so.4
    #5  0xb6fc24fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
    #6  0xb6bb1e5e in clone () from /lib/tls/i686/cmov/libc.so.6

    Thread 11 (Thread 0xad948b90 (LWP 5701)):
    #0  0xb7ee8410 in __kernel_vsyscall ()
    #1  0xb6fc6aa5 in pthread_cond_wait@@GLIBC_2.3.2 ()
       from /lib/tls/i686/cmov/libpthread.so.0
    #2  0xb720c924 in QWaitCondition::wait () from /usr/lib/libQtCore.so.4
    #3  0x0820eb3e in ?? ()
    #4  0xb720c057 in ?? () from /usr/lib/libQtCore.so.4
    #5  0xb6fc24fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
    #6  0xb6bb1e5e in clone () from /lib/tls/i686/cmov/libc.so.6

    Thread 9 (Thread 0xae2d1b90 (LWP 5699)):
    #0  0xb7ee8410 in __kernel_vsyscall ()
    ---Type <return> to continue, or q <return> to quit---
    #1  0xb6ba7c07 in poll () from /lib/tls/i686/cmov/libc.so.6
    #2  0x081ed399 in ?? ()
    #3  0xb720c057 in ?? () from /usr/lib/libQtCore.so.4
    #4  0xb6fc24fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
    #5  0xb6bb1e5e in clone () from /lib/tls/i686/cmov/libc.so.6

    Thread 8 (Thread 0xaeae4b90 (LWP 5698)):
    #0  0xb7ee8410 in __kernel_vsyscall ()
    #1  0xb6fc6aa5 in pthread_cond_wait@@GLIBC_2.3.2 ()
       from /lib/tls/i686/cmov/libpthread.so.0
    #2  0xb720c924 in QWaitCondition::wait () from /usr/lib/libQtCore.so.4
    #3  0x0818e939 in ?? ()
    #4  0xb720c057 in ?? () from /usr/lib/libQtCore.so.4
    #5  0xb6fc24fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
    #6  0xb6bb1e5e in clone () from /lib/tls/i686/cmov/libc.so.6

    Thread 7 (Thread 0xaf2e5b90 (LWP 5697)):
    #0  0xb7ee8410 in __kernel_vsyscall ()
    #1  0xb6b06085 in raise () from /lib/tls/i686/cmov/libc.so.6
    #2  0xb6b07a01 in abort () from /lib/tls/i686/cmov/libc.so.6
    #3  0xb6d16480 in __gnu_cxx::__verbose_terminate_handler ()
       from /usr/lib/libstdc++.so.6
    #4  0xb6d13d05 in ?? () from /usr/lib/libstdc++.so.6
    ---Type <return> to continue, or q <return> to quit---
    #5  0xb6d13d42 in std::terminate () from /usr/lib/libstdc++.so.6
    #6  0xb6d13e6a in __cxa_throw () from /usr/lib/libstdc++.so.6
    #7  0xb6d1449e in operator new () from /usr/lib/libstdc++.so.6
    #8  0xb6d1457d in operator new[] () from /usr/lib/libstdc++.so.6
    #9  0x0811d035 in ?? ()
    #10 0x08196074 in ?? ()
    #11 0x0818c683 in ?? ()
    #12 0xb720c057 in ?? () from /usr/lib/libQtCore.so.4
    #13 0xb6fc24fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
    #14 0xb6bb1e5e in clone () from /lib/tls/i686/cmov/libc.so.6

    Thread 6 (Thread 0xafae6b90 (LWP 5695)):
    #0  0xb7ee8410 in __kernel_vsyscall ()
    #1  0xb6baa881 in select () from /lib/tls/i686/cmov/libc.so.6
    #2  0xb72a5b97 in ?? () from /usr/lib/libQtCore.so.4
    #3  0xb720c057 in ?? () from /usr/lib/libQtCore.so.4
    #4  0xb6fc24fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
    #5  0xb6bb1e5e in clone () from /lib/tls/i686/cmov/libc.so.6

    Thread 5 (Thread 0xb3431b90 (LWP 5694)):
    #0  0xb7ee8410 in __kernel_vsyscall ()
    #1  0xb6ba7c07 in poll () from /lib/tls/i686/cmov/libc.so.6
    #2  0xb69da6b7 in ?? () from /usr/lib/libjack.so.0
    ---Type <return> to continue, or q <return> to quit---
    #3  0xb69dacda in jack_thread_wait () from /usr/lib/libjack.so.0
    #4  0xb69db0de in ?? () from /usr/lib/libjack.so.0
    #5  0xb69def3f in ?? () from /usr/lib/libjack.so.0
    #6  0xb6fc24fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
    #7  0xb6bb1e5e in clone () from /lib/tls/i686/cmov/libc.so.6

    Thread 4 (Thread 0xb3e59b90 (LWP 5689)):
    #0  0xb7ee8410 in __kernel_vsyscall ()
    #1  0xb6fc6aa5 in pthread_cond_wait@@GLIBC_2.3.2 ()
       from /lib/tls/i686/cmov/libpthread.so.0
    #2  0xb720c924 in QWaitCondition::wait () from /usr/lib/libQtCore.so.4
    #3  0x081d956e in ?? ()
    #4  0xb720c057 in ?? () from /usr/lib/libQtCore.so.4
    #5  0xb6fc24fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
    #6  0xb6bb1e5e in clone () from /lib/tls/i686/cmov/libc.so.6

    Thread 3 (Thread 0xb4e38b90 (LWP 5688)):
    #0  0xb7ee8410 in __kernel_vsyscall ()
    #1  0xb6fc6aa5 in pthread_cond_wait@@GLIBC_2.3.2 ()
       from /lib/tls/i686/cmov/libpthread.so.0
    #2  0xb720c924 in QWaitCondition::wait () from /usr/lib/libQtCore.so.4
    #3  0x08142305 in ?? ()
    #4  0xb720c057 in ?? () from /usr/lib/libQtCore.so.4
    ---Type <return> to continue, or q <return> to quit---
    #5  0xb6fc24fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
    #6  0xb6bb1e5e in clone () from /lib/tls/i686/cmov/libc.so.6

    Thread 2 (Thread 0xb5b58b90 (LWP 5687)):
    #0  0xb7ee8410 in __kernel_vsyscall ()
    #1  0xb6ba229b in read () from /lib/tls/i686/cmov/libc.so.6
    #2  0xb6b400d9 in ?? () from /lib/tls/i686/cmov/libc.so.6
    #3  0xb6b422a8 in _IO_sgetn () from /lib/tls/i686/cmov/libc.so.6
    #4  0xb6b362ee in fread () from /lib/tls/i686/cmov/libc.so.6
    #5  0xb729dede in ?? () from /usr/lib/libQtCore.so.4
    #6  0xb72a27d3 in ?? () from /usr/lib/libQtCore.so.4
    #7  0xb729d634 in QFSFileEngine::read () from /usr/lib/libQtCore.so.4
    #8  0xb7260e13 in QFile::readData () from /usr/lib/libQtCore.so.4
    #9  0xb72692b8 in QIODevice::read () from /usr/lib/libQtCore.so.4
    #10 0x0811d05d in ?? ()
    #11 0x08196074 in ?? ()
    #12 0x0813e9af in ?? ()
    #13 0x08141bc3 in ?? ()
    #14 0x08142344 in ?? ()
    #15 0xb720c057 in ?? () from /usr/lib/libQtCore.so.4
    #16 0xb6fc24fb in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
    #17 0xb6bb1e5e in clone () from /lib/tls/i686/cmov/libc.so.6

    ---Type <return> to continue, or q <return> to quit---
    Thread 1 (Thread 0xb622f740 (LWP 5686)):
    #0  0xb7ee8410 in __kernel_vsyscall ()
    #1  0xb6fc96bc in __lll_unlock_wake () from /lib/tls/i686/cmov/libpthread.so.0
    #2  0xb6fc5e0a in _L_unlock_194 () from /lib/tls/i686/cmov/libpthread.so.0
    #3  0xb6fc5afe in __pthread_mutex_unlock_usercnt ()
       from /lib/tls/i686/cmov/libpthread.so.0
    #4  0xb720cab1 in QWaitCondition::wakeAll () from /usr/lib/libQtCore.so.4
    #5  0x08158adc in ?? ()
    #6  0x0816e969 in ?? ()
    #7  0x0822066d in ?? ()
    #8  0xb72d3cf4 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
    #9  0xb72d4050 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
    #10 0xb768ea01 in QAction::triggered () from /usr/lib/libQtGui.so.4
    #11 0xb768f62f in QAction::activate () from /usr/lib/libQtGui.so.4
    #12 0xb7a1456f in ?? () from /usr/lib/libQtGui.so.4
    #13 0xb7a153b1 in QMenu::mouseReleaseEvent () from /usr/lib/libQtGui.so.4
    #14 0xb76defbd in QWidget::event () from /usr/lib/libQtGui.so.4
    #15 0xb7a127c5 in QMenu::event () from /usr/lib/libQtGui.so.4
    #16 0xb769528d in QApplicationPrivate::notify_helper ()
       from /usr/lib/libQtGui.so.4
    #17 0xb76994f1 in QApplication::notify () from /usr/lib/libQtGui.so.4
    #18 0xb72c0c1b in QCoreApplication::notifyInternal ()
       from /usr/lib/libQtCore.so.4
    ---Type <return> to continue, or q <return> to quit---
    #19 0xb76f2638 in ?? () from /usr/lib/libQtGui.so.4
    #20 0xb76f1197 in QApplication::x11ProcessEvent () from /usr/lib/libQtGui.so.4
    #21 0xb7716684 in ?? () from /usr/lib/libQtGui.so.4
    #22 0xb7103dd6 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
    #23 0xb7107193 in ?? () from /usr/lib/libglib-2.0.so.0
    #24 0xb710774e in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
    #25 0xb72e4f82 in QEventDispatcherGlib::processEvents ()
       from /usr/lib/libQtCore.so.4
    #26 0xb7716475 in ?? () from /usr/lib/libQtGui.so.4
    #27 0xb72bffb2 in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
    #28 0xb72c00bc in QEventLoop::exec () from /usr/lib/libQtCore.so.4
    #29 0xb7a15639 in QMenu::exec () from /usr/lib/libQtGui.so.4
    #30 0x0817b38b in ?? ()
    #31 0xb76defbd in QWidget::event () from /usr/lib/libQtGui.so.4
    #32 0xb79d3433 in QFrame::event () from /usr/lib/libQtGui.so.4
    #33 0xb7a5951f in QAbstractScrollArea::viewportEvent ()
       from /usr/lib/libQtGui.so.4
    #34 0xb7adf248 in QAbstractItemView::viewportEvent ()
       from /usr/lib/libQtGui.so.4
    #35 0xb7a5a715 in ?? () from /usr/lib/libQtGui.so.4
    #36 0xb7695242 in QApplicationPrivate::notify_helper ()
       from /usr/lib/libQtGui.so.4
    #37 0xb7699237 in QApplication::notify () from /usr/lib/libQtGui.so.4
    ---Type <return> to continue, or q <return> to quit---
    #38 0xb72c0c1b in QCoreApplication::notifyInternal ()
       from /usr/lib/libQtCore.so.4
    #39 0xb76f21e5 in ?? () from /usr/lib/libQtGui.so.4
    #40 0xb76f1197 in QApplication::x11ProcessEvent () from /usr/lib/libQtGui.so.4
    #41 0xb7716684 in ?? () from /usr/lib/libQtGui.so.4
    #42 0xb7103dd6 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
    #43 0xb7107193 in ?? () from /usr/lib/libglib-2.0.so.0
    #44 0xb710774e in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
    #45 0xb72e4f82 in QEventDispatcherGlib::processEvents ()
       from /usr/lib/libQtCore.so.4
    #46 0xb7716475 in ?? () from /usr/lib/libQtGui.so.4
    #47 0xb72bffb2 in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
    #48 0xb72c00bc in QEventLoop::exec () from /usr/lib/libQtCore.so.4
    #49 0xb72c288a in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
    #50 0xb76946e7 in QApplication::exec () from /usr/lib/libQtGui.so.4
    #51 0x080f4fd4 in ?? ()
    #52 0xb6af1450 in __libc_start_main () from /lib/tls/i686/cmov/libc.so.6
    #53 0x080605b1 in ?? ()
    #0  0xb7ee8410 in __kernel_vsyscall ()

    Hope this helps.

**Comment by Holzhaus** [comment]
Created by: gamegod
Date: 2008-10-01T05:16:31Z

    Hello again,

    Yes, this certainly was useful. So this is just to confirm once again, this is ALL mp3s that are crashing?

    I assume you're using the version of Qt4 that came with Ubuntu 8.04, right?

    One point of interest here is your videocard - The integrated Intel 855GM. Intel generally has good drivers, but we've seen Mixxx crash due to crazy drivers many times before. It could also be a problem with compiz....
    (The reason the video stuff is significant is because the waveform view uses OpenGL, while the "simple" view does not. Problems with the OpenGL waveform is usually a strong indicator of some driver or X server problem.)

    Have you tried disabled compiz? (Go into System->Preferences->Appearance, and turn the effects stuff off.)

    Thanks again,
    Albert

**Comment by Holzhaus** [comment]
Created by: lanquarden
Date: 2008-10-01T15:36:33Z

    I found out some weird stuff, acting on your hints about the graphics card I did the following.

    Checked the graphics driver, apparently Ubuntu Studio wasn't using the intel driver, solved that by adding the line Driver  "intel" in xorg.conf. Checked if I had direct rendering enabled by glxinfo. I didn't have compiz enabled so that couldn't be the problem.

    Then I went ahead and tried mixxx again, with the same result. Tried with even more mp3s of my collection and mixxx crashed on me every single time.

    I use the BCD3000 with mixxx, with Jack configured like this:
    jackd -R -P 70 -d alsa -d hw:1 -P hw:1 -p 128 -n 2 -r 44100 -m -o 4

    Now at some time the power went out, so I couldn't continue with trying with the BCD3000. I have a laptop so I tried with no soundcard configured and all of a sudden it worked, mixxx didn't crash on me, loading nicely every single mp3 I gave it.

    When power came back I fired up Jack again, started mixxx again but forgot to put the soundcard configuration back to Jack, leaving it with no soundcard configuration. Tried it and some mp3s would load others led to a crash of mixxx. 

    And when I configure mixxx to use Jack, it crashes on every single mp3 that i try to load.

    Now I'm confused, is it due to my realtime/jack setup? I hope you have more hints with what the problem could be. I really would like to use jack because of its performance and the many possibilities.

    Thanks!

**Comment by Holzhaus** [comment]
Created by: @Pegasus-RPG
Date: 2009-07-15T10:17:47Z

    lanquarden: Please try with the 1.7.0~beta1 and let us know if it's any better.

**Comment by Holzhaus** [comment]
Issue closed with status "Invalid".
