### ISSUE TITLE
Crashing when with GLSL (RGB or Filtered) waveforms

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#223]
start with a clean profile (no profile), no controller attached.
Deere > Tango ----= crash
 restart with Deere
Deere > Shade ----= works
Shade > LateNight = works
LateNight > Deere = works
Deere > Tango ----= works
Tango > LateNight = crash
 restarts with LateNight
LateNight > Tango = crash
 restarts with Tango
Tango > Tango64 --= crash
 restarts with Tango
Tango > Tango64 --= works

How to debug this?
I don't see a pattern and no relevant messages in the log when running
mixxx --developer.

Ubuntu Studio 14.04 (xfce4) 64bit
kernel 3.14.23-rt20 #1 SMP PREEMPT RT

**Comment by Holzhaus** [comment]
(by daschuer)
We need a backtrace from the crash. https://www.mixxx.org/wiki/doku.php/creating_backtraces

**Comment by Holzhaus** [comment]
(by be.ing)
I cannot reproduce this.

**Comment by Holzhaus** [comment]
(by uklotzde)
I also don't experience any crashes when switching skins. Maybe dependent on and limited to this ancient Ubuntu Studio version?

**Comment by Holzhaus** [comment]
(by ronso0)
here's the backtrace

**Comment by Holzhaus** [comment]
(by daschuer)
It looks like a gl related crash in you graphic diver. Does it also crash if you choose bin gl waveforms?

I can also imagine that this is a delayed event sent to a deleted waveform. 


Thread 1 (Thread 0x7ffff7fa28c0 (LWP 3790)):
#0  0x0000000000000000 in ?? ()
#1  0x00007fff090bca65 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#2  0x00007fff090b8a57 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#3  0x00007fff090bf82f in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#4  0x00007ffff73ef373 in QGL2PaintEngineEx::begin(QPaintDevice*) () from /usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4
#5  0x00007ffff5f3514b in QPainter::begin(QPaintDevice*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#6  0x00007ffff5f35ab8 in QPainter::QPainter(QPaintDevice*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#7  0x0000000000c543a1 in ?? ()
#8  0x0000000000c503fe in ?? ()
#9  0x0000000000c1efcd in ?? ()

**Comment by Holzhaus** [comment]
(by ronso0)
Yes, when I use GL waveforms it works.

**Comment by Holzhaus** [comment]
(by daschuer)
Itetesting, I thought it would be the opposite.
Can you tell us what exactly is the effected waveform?

**Comment by Holzhaus** [comment]
(by ronso0)
it's crashing when I have GLSL (RGB or Filtered) set.
I just switched skins without problems with GL set, then it crashed when I chose Filtered GLSL.

**Comment by Holzhaus** [comment]
(by ronso0)
..without switching skins, just selecting RGB (GLSL)

**Comment by Holzhaus** [comment]
(by rryan)
rons0 does this still occur with Mixxx 2.1.4 or 2.2.0 beta?

**Comment by Holzhaus** [comment]
(by ronso0)
it doesn't happen anymore with

mixxx 2.1.4
Ubuntu Studio 18.04
4.16.0-041600-lowlatency

**Comment by Holzhaus** [comment]
(by rryan)
Let's assume it was fixed in 2.1.x then. Thanks!
