### ISSUE TITLE
QT5, crash when loading a Qt4 Soundsource / Vamp Plug-In

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#229]
Unfortunately changing the API version has no effect, because it crashes during resolving the symbols. I propose to change the installation directory to 
"/usr/local/lib/mixxx/plugins/soundsourceqt5"

Program received signal SIGSEGV, Segmentation fault.
QList (this=0x7fffca7fa4f8 <QPrinterInfoPrivate::shared_null+24>)
    at ../../include/QtCore/../../src/corelib/tools/qlist.h:121
121	    { qSwap(d, other.d); return *this; }
(gdb) bt
#0  QList (this=0x7fffca7fa4f8 <QPrinterInfoPrivate::shared_null+24>)
    at ../../include/QtCore/../../src/corelib/tools/qlist.h:121
#1  QPrinterInfoPrivate (name="", 
    this=0x7fffca7fa4e0 <QPrinterInfoPrivate::shared_null>)
    at painting/qprinterinfo_p.h:71
#2  __static_initialization_and_destruction_0 (__initialize_p=1, 
    __priority=65535) at painting/qprinterinfo.cpp:35
#3  _GLOBAL__sub_I_qprinterinfo.cpp(void) () at painting/qprinterinfo.cpp:163
#4  0x00007ffff7dea1da in call_init (l=<optimized out>, argc=argc@entry=1, 
    argv=argv@entry=0x7fffffffdff8, env=env@entry=0x7fffffffe008)
    at dl-init.c:78
#5  0x00007ffff7dea2c3 in call_init (env=<optimized out>, 
    argv=<optimized out>, argc=<optimized out>, l=<optimized out>)
    at dl-init.c:36
#6  _dl_init (main_map=main_map@entry=0x167b450, argc=1, argv=0x7fffffffdff8, 
    env=0x7fffffffe008) at dl-init.c:126
#7  0x00007ffff7deed00 in dl_open_worker (a=a@entry=0x7fffffffd378)
    at dl-open.c:577
#8  0x00007ffff7dea094 in _dl_catch_error (
    objname=objname@entry=0x7fffffffd368, 
    errstring=errstring@entry=0x7fffffffd370, 
    mallocedp=mallocedp@entry=0x7fffffffd360, 
    operate=operate@entry=0x7ffff7deea30 <dl_open_worker>, 
---Type <return> to continue, or q <return> to quit---
    args=args@entry=0x7fffffffd378) at dl-error.c:187
#9  0x00007ffff7dee44b in _dl_open (
    file=0x166fe08 "/usr/local/lib/mixxx/plugins/soundsource/libsoundsourcem4a.so_", mode=-2147483647, caller_dlopen=<optimized out>, nsid=-2, argc=1, 
    argv=0x7fffffffdff8, env=0x7fffffffe008) at dl-open.c:661
#10 0x00007ffff1b2102b in dlopen_doit (a=a@entry=0x7fffffffd590) at dlopen.c:66
#11 0x00007ffff7dea094 in _dl_catch_error (objname=0x145a320, 
    errstring=0x145a328, mallocedp=0x145a318, 
    operate=0x7ffff1b20fd0 <dlopen_doit>, args=0x7fffffffd590)
    at dl-error.c:187
#12 0x00007ffff1b2162d in _dlerror_run (
    operate=operate@entry=0x7ffff1b20fd0 <dlopen_doit>, 
    args=args@entry=0x7fffffffd590) at dlerror.c:163
#13 0x00007ffff1b210c1 in __dlopen (file=<optimized out>, mode=<optimized out>)
    at dlopen.c:87
#14 0x00007ffff497fe3a in QLibraryPrivate::load_sys (this=0x167ab10)
    at plugin/qlibrary_unix.cpp:230
#15 0x00007ffff497b095 in QLibraryPrivate::load (this=0x167ab10)
    at plugin/qlibrary.cpp:514
#16 0x00007ffff497b2bc in QLibrary::load (this=this@entry=0x16707e0)
    at plugin/qlibrary.cpp:765
#17 0x0000000000bd2ae0 in mixxx::SoundSourcePluginLibrary::init (
    this=0x16707d8) at src/sources/soundsourcepluginlibrary.cpp:46

**Comment by Holzhaus** [comment]
(by be.ing)
Why would a user still have the Qt4 plugin after upgrading?

**Comment by Holzhaus** [comment]
(by daschuer)
Because we do not distribute for example the m4a plugIn. They may have it from an old build, experience the crash the first time.

**Comment by Holzhaus** [comment]
(by poelzi)
I had the crash trough vamp which was quite puzzeling. Removing the old installation fixed the problem.

**Comment by Holzhaus** [comment]
(by daschuer)
Related https://bugs.launchpad.net/mixxx/+bug/1711173

**Comment by Holzhaus** [comment]
(by daschuer)
https://github.com/mixxxdj/mixxx/pull/1698

**Comment by Holzhaus** [comment]
(by daschuer)
This was confirmed in https://bugs.launchpad.net/mixxx/+bug/1711173
