### ISSUE TITLE
QT5: Crash when switching Big effects in Dark Metal

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#232]
this was tested with master, Qt5 and https://github.com/mixxxdj/mixxx/pull/1318 on Ubuntu Trusty 64 bit. 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff52af074 in QPaintEngine::paintDevice (this=0x3c03f700)
    at painting/qpaintengine.cpp:900
900	    return d_func()->pdev;
(gdb) bt
#0  0x00007ffff52af074 in QPaintEngine::paintDevice (this=0x3c03f700)
    at painting/qpaintengine.cpp:900
#1  0x00007ffff5800bab in QWidget::render (this=0x3d6447a0, 
    painter=painter@entry=0x7fffffffb420, targetOffset=..., sourceRegion=..., 
    renderFlags=renderFlags@entry=...) at kernel/qwidget.cpp:4726
#2  0x00000000009d220c in PreviewButtonDelegate::paintItem (this=0x3c962a50, 
    painter=0x7fffffffb420, option=..., index=...)
    at src/library/previewbuttondelegate.cpp:93
#3  0x0000000000a13aa5 in TableItemDelegate::paint (this=0x3c962a50, 
    painter=0x7fffffffb420, option=..., index=...)
    at src/library/tableitemdelegate.cpp:45
#4  0x00007ffff5a21100 in QTableViewPrivate::drawCell (
    this=this@entry=0x3d627060, painter=painter@entry=0x7fffffffb420, 
    option=..., index=...) at itemviews/qtableview.cpp:930
#5  0x00007ffff5a2aa5b in QTableView::paintEvent (this=0x3d626560, 
    event=<optimized out>) at itemviews/qtableview.cpp:1486
#6  0x00007ffff5803302 in QWidget::event (this=this@entry=0x3d626560, 
    event=event@entry=0x7fffffffbb00) at kernel/qwidget.cpp:8098
#7  0x00007ffff58fec7e in QFrame::event (this=0x3d626560, e=0x7fffffffbb00)
    at widgets/qframe.cpp:534
#8  0x00007ffff59ffd5b in QAbstractItemView::viewportEvent (this=0x3d626560, 
    event=0x7fffffffbb00) at itemviews/qabstractitemview.cpp:1689
#9  0x00007ffff4982e53 in QCoreApplicationPrivate::sendThroughObjectEventFilters---Type <return> to continue, or q <return> to quit---
 (this=this@entry=0x145a430, receiver=receiver@entry=0x3d6279e0, 
    event=event@entry=0x7fffffffbb00) at kernel/qcoreapplication.cpp:977
#10 0x00007ffff57c7c6c in QApplicationPrivate::notify_helper (
    this=this@entry=0x145a430, receiver=receiver@entry=0x3d6279e0, 
    e=e@entry=0x7fffffffbb00) at kernel/qapplication.cpp:3482
#11 0x00007ffff57cce56 in QApplication::notify (this=0x7fffffffdd80, 
    receiver=0x3d6279e0, e=0x7fffffffbb00) at kernel/qapplication.cpp:3236
#12 0x00007ffff4982c2d in QCoreApplication::notifyInternal (this=
    0x7fffffffdd80, receiver=receiver@entry=0x3d6279e0, 
    event=event@entry=0x7fffffffbb00) at kernel/qcoreapplication.cpp:881
#13 0x00007ffff57fdbea in sendSpontaneousEvent (event=0x7fffffffbb00, 
    receiver=0x3d6279e0)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:235
#14 QWidgetPrivate::drawWidget (this=this@entry=0x3d6262d0, pdev=pdev@entry=
    0x17127d0, rgn=..., offset=..., flags=flags@entry=4, 
    sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5138
#15 0x00007ffff57fe5bc in QWidgetPrivate::paintSiblingsRecursive (
    this=this@entry=0x3d627060, pdev=pdev@entry=0x17127d0, 
    siblings=QList<QObject *> (size = 58) = {...}, index=<optimized out>, 
    index@entry=47, rgn=..., offset=..., flags=flags@entry=4, 
    sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5332
---Type <return> to continue, or q <return> to quit---
#16 0x00007ffff57fe434 in QWidgetPrivate::paintSiblingsRecursive (
    this=this@entry=0x3d627060, pdev=pdev@entry=0x17127d0, 
    siblings=QList<QObject *> (size = 58) = {...}, index=47, index@entry=55, 
    rgn=..., offset=..., flags=flags@entry=4, 
    sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5319
#17 0x00007ffff57fe434 in QWidgetPrivate::paintSiblingsRecursive (
    this=this@entry=0x3d627060, pdev=pdev@entry=0x17127d0, 
    siblings=QList<QObject *> (size = 58) = {...}, index=55, index@entry=56, 
    rgn=..., offset=..., flags=flags@entry=4, 
    sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5319
#18 0x00007ffff57fe434 in QWidgetPrivate::paintSiblingsRecursive (
    this=this@entry=0x3d627060, pdev=pdev@entry=0x17127d0, 
    siblings=QList<QObject *> (size = 58) = {...}, index=56, rgn=..., 
    offset=..., flags=flags@entry=4, sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5319
#19 0x00007ffff57fd786 in QWidgetPrivate::drawWidget (
    this=this@entry=0x3d627060, pdev=pdev@entry=0x17127d0, rgn=..., 
    offset=..., flags=flags@entry=4, sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5189
#20 0x00007ffff57fe5bc in QWidgetPrivate::paintSiblingsRecursive (
    this=this@entry=0x3d624880, pdev=pdev@entry=0x17127d0, 
---Type <return> to continue, or q <return> to quit---
    siblings=QList<QObject *> (size = 11) = {...}, index=<optimized out>, 
    rgn=..., offset=..., flags=flags@entry=4, 
    sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5332
#21 0x00007ffff57fd786 in QWidgetPrivate::drawWidget (
    this=this@entry=0x3d624880, pdev=pdev@entry=0x17127d0, rgn=..., 
    offset=..., flags=flags@entry=4, sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5189
#22 0x00007ffff57fe5bc in QWidgetPrivate::paintSiblingsRecursive (
    this=this@entry=0x3d6201d0, pdev=pdev@entry=0x17127d0, 
    siblings=QList<QObject *> (size = 2) = {...}, index=<optimized out>, 
    rgn=..., offset=..., flags=flags@entry=4, 
    sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5332
#23 0x00007ffff57fd786 in QWidgetPrivate::drawWidget (
    this=this@entry=0x3d6201d0, pdev=pdev@entry=0x17127d0, rgn=..., 
    offset=..., flags=flags@entry=4, sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5189
#24 0x00007ffff57fe5bc in QWidgetPrivate::paintSiblingsRecursive (
    this=this@entry=0x3d5910d0, pdev=pdev@entry=0x17127d0, 
    siblings=QList<QObject *> (size = 4) = {...}, index=<optimized out>, 
    index@entry=0, rgn=..., offset=..., flags=flags@entry=4, 
    sharedPainter=sharedPainter@entry=0x0, 
---Type <return> to continue, or q <return> to quit---
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5332
#25 0x00007ffff57fe434 in QWidgetPrivate::paintSiblingsRecursive (
    this=this@entry=0x3d5910d0, pdev=pdev@entry=0x17127d0, 
    siblings=QList<QObject *> (size = 4) = {...}, index=0, index@entry=2, 
    rgn=..., offset=..., flags=flags@entry=4, 
    sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5319
#26 0x00007ffff57fe434 in QWidgetPrivate::paintSiblingsRecursive (
    this=this@entry=0x3d5910d0, pdev=pdev@entry=0x17127d0, 
    siblings=QList<QObject *> (size = 4) = {...}, index=2, rgn=..., 
    offset=..., flags=flags@entry=4, sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5319
#27 0x00007ffff57fd786 in QWidgetPrivate::drawWidget (
    this=this@entry=0x3d5910d0, pdev=pdev@entry=0x17127d0, rgn=..., 
    offset=..., flags=flags@entry=4, sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5189
#28 0x00007ffff57fe5bc in QWidgetPrivate::paintSiblingsRecursive (
    this=this@entry=0x3d58cfb0, pdev=pdev@entry=0x17127d0, 
    siblings=QList<QObject *> (size = 4) = {...}, index=<optimized out>, 
    index@entry=2, rgn=..., offset=..., flags=flags@entry=4, 
    sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5332
#29 0x00007ffff57fe434 in QWidgetPrivate::paintSiblingsRecursive (
---Type <return> to continue, or q <return> to quit---
    this=this@entry=0x3d58cfb0, pdev=pdev@entry=0x17127d0, 
    siblings=QList<QObject *> (size = 4) = {...}, index=2, rgn=..., 
    offset=..., flags=flags@entry=4, sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5319
#30 0x00007ffff57fd786 in QWidgetPrivate::drawWidget (
    this=this@entry=0x3d58cfb0, pdev=pdev@entry=0x17127d0, rgn=..., 
    offset=..., flags=flags@entry=4, sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5189
#31 0x00007ffff57fe5bc in QWidgetPrivate::paintSiblingsRecursive (
    this=this@entry=0x3c7f8330, pdev=pdev@entry=0x17127d0, 
    siblings=QList<QObject *> (size = 5) = {...}, index=<optimized out>, 
    rgn=..., offset=..., flags=flags@entry=4, 
    sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5332
#32 0x00007ffff57fd786 in QWidgetPrivate::drawWidget (
    this=this@entry=0x3c7f8330, pdev=pdev@entry=0x17127d0, rgn=..., 
    offset=..., flags=flags@entry=4, sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5189
#33 0x00007ffff57fe5bc in QWidgetPrivate::paintSiblingsRecursive (
    this=this@entry=0x343e33e0, pdev=pdev@entry=0x17127d0, 
    siblings=QList<QObject *> (size = 151) = {...}, index=<optimized out>, 
    rgn=..., offset=..., flags=flags@entry=4, 
    sharedPainter=sharedPainter@entry=0x0, 
---Type <return> to continue, or q <return> to quit---
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5332
#34 0x00007ffff57fd786 in QWidgetPrivate::drawWidget (
    this=this@entry=0x343e33e0, pdev=pdev@entry=0x17127d0, rgn=..., 
    offset=..., flags=flags@entry=4, sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5189
#35 0x00007ffff57fe5bc in QWidgetPrivate::paintSiblingsRecursive (
    this=this@entry=0x1671630, pdev=pdev@entry=0x17127d0, 
    siblings=QList<QObject *> (size = 9) = {...}, index=<optimized out>, 
    rgn=..., offset=..., flags=flags@entry=4, 
    sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5332
#36 0x00007ffff57fd786 in QWidgetPrivate::drawWidget (this=0x1671630, 
    pdev=0x17127d0, rgn=..., offset=..., flags=flags@entry=5, 
    sharedPainter=sharedPainter@entry=0x0, 
    backingStore=backingStore@entry=0x1682e20) at kernel/qwidget.cpp:5189
#37 0x00007ffff57d4233 in QWidgetBackingStore::sync (this=0x1682e20)
    at kernel/qwidgetbackingstore.cpp:1081
#38 0x00007ffff57f3e2f in QWidgetPrivate::syncBackingStore (
    this=this@entry=0x1671630) at kernel/qwidget.cpp:1686
#39 0x00007ffff5803112 in QWidget::event (this=0x7fffffffddb0, 
    event=0x36f4e8b0) at kernel/qwidget.cpp:8236
#40 0x00007ffff57c7c8c in QApplicationPrivate::notify_helper (
    this=this@entry=0x145a430, receiver=receiver@entry=0x7fffffffddb0, 
---Type <return> to continue, or q <return> to quit---
    e=e@entry=0x36f4e8b0) at kernel/qapplication.cpp:3486
#41 0x00007ffff57cce56 in QApplication::notify (this=0x7fffffffdd80, 
    receiver=0x7fffffffddb0, e=0x36f4e8b0) at kernel/qapplication.cpp:3236
#42 0x00007ffff4982c2d in QCoreApplication::notifyInternal (
    this=0x7fffffffdd80, receiver=0x7fffffffddb0, event=event@entry=0x36f4e8b0)
    at kernel/qcoreapplication.cpp:881
#43 0x00007ffff4984e07 in sendEvent (event=0x36f4e8b0, 
    receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:232
#44 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, 
    event_type=event_type@entry=0, data=0x1451bb0)
    at kernel/qcoreapplication.cpp:1485
#45 0x00007ffff4985433 in QCoreApplication::sendPostedEvents (
    receiver=receiver@entry=0x0, event_type=event_type@entry=0)
    at kernel/qcoreapplication.cpp:1343
#46 0x00007ffff49cfcd3 in postEventSourceDispatch (s=0x1515e30)
    at kernel/qeventdispatcher_glib.cpp:279
#47 0x00007ffff0f2ae04 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007ffff0f2b048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007ffff0f2b0ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#50 0x00007ffff49cf98c in QEventDispatcherGlib::processEvents (this=0x1530e00, 
---Type <return> to continue, or q <return> to quit---
    flags=...) at kernel/qeventdispatcher_glib.cpp:426
#51 0x00007ffff498196b in QEventLoop::exec (this=this@entry=0x7fffffffdc90, 
    flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#52 0x00007ffff49880e1 in QCoreApplication::exec ()
    at kernel/qcoreapplication.cpp:1134
#53 0x00007ffff511a11c in QGuiApplication::exec ()
    at kernel/qguiapplication.cpp:1343
#54 0x00007ffff57c6605 in QApplication::exec () at kernel/qapplication.cpp:2711
#55 0x0000000000475413 in runMixxx (args=..., app=0x7fffffffdd80)
    at src/main.cpp:53
#56 main (argc=1, argv=<optimized out>) at src/main.cpp:132

**Comment by Holzhaus** [comment]
(by daschuer)
The 2.1 branch using qt4 is not effected

**Comment by Holzhaus** [comment]
(by rryan)
Does this still happen?

**Comment by Holzhaus** [comment]
(by daschuer)
I cannot reproduce it with 2.2.1 
I guess RJ has fixed it.
