### ISSUE TITLE
deadlock on 2.4 marker drawing code

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#275]
Mixxx 2.4 (personal integration branch but nothing touches this part). I suspect its a 2.3 bug as well.

I think I have seen this before. I saved a coredump and could provide the nix derivate used.

#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f1d9b223b21 in QSemaphore::acquire(int) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Core.so.5
#2  0x00007f1d9c7a297f in ?? () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Gui.so.5
#3  0x00007f1d9c56d97c in QImage::smoothScaled(int, int) const () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Gui.so.5
#4  0x00007f1d9c57068a in QImage::transformed(QTransform const&, Qt::TransformationMode) const () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Gui.so.5
#5  0x00007f1d9c570c30 in QImage::scaled(QSize const&, Qt::AspectRatioMode, Qt::TransformationMode) const () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Gui.so.5
#6  0x0000000000b0851a in WOverview::drawWaveformPixmap(QPainter*) ()
#7  0x0000000000b0eb12 in WOverview::paintEvent(QPaintEvent*) ()
#8  0x00007f1d9cdd427e in QWidget::event(QEvent*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#9  0x0000000000b58e08 in WWidget::event(QEvent*) ()
#10 0x00007f1d9cd91cef in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#11 0x00007f1d9cd9ab50 in QApplication::notify(QObject*, QEvent*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#12 0x00007f1d9b40a7fa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Core.so.5
#13 0x00007f1d9cdcc896 in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#14 0x00007f1d9cdcd0db in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#15 0x00007f1d9cdce51b in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#16 0x00007f1d9cdccdec in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#17 0x00007f1d9cdce51b in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#18 0x00007f1d9cdce3fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#19 0x00007f1d9cdce3fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#20 0x00007f1d9cdccdec in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#21 0x00007f1d9cdce51b in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#22 0x00007f1d9cdce3fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#23 0x00007f1d9cdccdec in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#24 0x00007f1d9cdce51b in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#25 0x00007f1d9cdce3fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#26 0x00007f1d9cdccdec in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#27 0x00007f1d9cdce51b in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#28 0x00007f1d9cdce3fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#29 0x00007f1d9cdccdec in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#30 0x00007f1d9cdce51b in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /nix/store/5rqsaf7in0xx44ky97alz7q62y2bdb35-qtbase-5.15.0/lib/libQt5Widgets.so.5
#31 0x00007f1d9cdce3fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManag

**Comment by Holzhaus** [comment]
(by be.ing)
The deadlock is inside Qt. Can you reproduce this with other versions of Qt? Is there anything that may be relevant on the Qt bug tracker?

**Comment by Holzhaus** [comment]
(by uklotzde)
Known issues in Qt 5.15.0 that has been fixed in Qt 5.15.1:

https://bugreports.qt.io/browse/QTBUG-84619
