### ISSUE TITLE
ControlObject Asserts

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#293]
Many users (dev team included) have been reporting ControlObject ASSERTs getting fired semi-randomly. This meta-bug is intended to be a central place for us to gather data on whatever's causing them. It could be incorrect ControlObject usage, some strange race condition, or something else altogether.

First bit of data: http://rafb.net/p/u37aZF58.txt
Relevant part of backtrace:

Thread 1 (Thread 0x7feb7dcaf7e0 (LWP 4388)):
#0  0x00007feb839510e5 in raise () from /lib/libc.so.6
#1  0x00007feb83952b40 in abort () from /lib/libc.so.6
#2  0x000000000048bd76 in MessageOutput (type=QtFatalMsg,
    msg=0x7fff925621d0 "ASSERT: \"m_pControlObject\" in file src/controlobjectthread.cpp, line 32")
    at src/main.cpp:93
#3  0x00007feb8636168e in qt_message_output () from /usr/lib/libQtCore.so.4
#4  0x00007feb863617fd in qFatal () from /usr/lib/libQtCore.so.4
#5  0x00000000004324ac in ControlObjectThread (this=0x1154070, pControlObject=0x0)
    at src/controlobjectthread.cpp:32
#6  0x0000000000508a2d in Hercules::selectMapping (this=0xdc5330, qMapping=@0x7fff92565340)
    at src/hercules.cpp:189
#7  0x000000000050b725 in Hercules (this=0xdc5330) at src/hercules.cpp:69
#8  0x000000000053b973 in HerculesLinux (this=0xdc5330) at src/herculeslinux.cpp:78
#9  0x000000000044af8b in DlgPrefMidi (this=0xde7c90, parent=0x113c930, pConfig=0x9fc5d0)
    at src/dlgprefmidi.cpp:214
#10 0x0000000000438f1a in DlgPreferences (this=0x113c930, mixxx=0x9906b0, view=0xa96110,
    soundman=0xa62d80, track=0xb03400, _config=0x9fc5d0) at src/dlgpreferences.cpp:62
#11 0x00000000004999ff in MixxxApp (this=0x9906b0, a=0x94bf00, args=@0x7fff925667d0, pSplash=0x0)
    at src/mixxx.cpp:295
#12 0x000000000048b9ea in main (argc=1, argv=0x7fff925669d8) at src/main.cpp:208
(gdb)

**Comment by Holzhaus** [comment]
(by gamegod)
Garth fixed this one... If we get more ControlObject asserts, we'll open a new bug

**Comment by Holzhaus** [comment]
(by ironstorm-gmail)
hahaha, yeah I "fixed" that one....
