### ISSUE TITLE
Segfault when closing mixxx

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#427]
I noticed that mixxx exits with a segfault on debian sid after revision 3345.

here is the back trace for the segfault

#0  0x00007ffff160a702 in libusb_exit () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#1  0x00000000007d194b in hid_exit () at lib/hidapi-0.7.0/linux/hid-libusb.c:399
#2  0x00000000007cf2e5 in HidEnumerator::~HidEnumerator (this=0x16d6b90, 
    __in_chrg=<optimized out>) at src/controllers/hid/hidenumerator.cpp:22
#3  0x00000000007cf489 in HidEnumerator::~HidEnumerator (this=0x16d6b90, 
    __in_chrg=<optimized out>) at src/controllers/hid/hidenumerator.cpp:23
#4  0x000000000053dba9 in ControllerManager::slotShutdown (this=0x167c5b0)
    at src/controllers/controllermanager.cpp:136
#5  0x0000000000874db8 in ControllerManager::qt_static_metacall (_o=0x167c5b0, 
    _c=<optimized out>, _id=<optimized out>, _a=0x2a656c0)
    at lin64_build/controllers/moc_controllermanager.cc:93

the problem does not occur in wheezy. So I'm not sure if the bug is in the debian package, libusb-1.0-0, or if there is a error in mixxx.

**Comment by Holzhaus** [comment]
(by rryan)
thanks -- fixed now

The issue was that hidapi and our new Bulk USB system both used libusb without a private context.
