### ISSUE TITLE
statsmanager crash backtrace

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#435]
This was on exit.  Last lines of the log:

Debug [Main]: ~MixxxApp: All leaking controls deleted. 
*** glibc detected *** /home/owen/src/launchpad/DJO-hacks-trunk/mixxx/mixxx: free(): invalid pointer: 0x00007fffa4000ea0 ***

(gdb) bt
#0  0x00007ffff088c425 in __GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007ffff088fb8b in __GI_abort () at abort.c:91
#2  0x00007ffff08ca39e in __libc_message (do_abort=2, fmt=0x7ffff09d4008 "*** glibc detected *** %s: %s: 0x%s ***\n")
    at ../sysdeps/unix/sysv/linux/libc_fatal.c:201
#3  0x00007ffff08d4b96 in malloc_printerr (action=3, str=0x7ffff09d0913 "free(): invalid pointer", ptr=<optimized out>) at malloc.c:5007
#4  0x00000000005d58df in StatsManager::processIncomingStatReports (this=0xc946b0) at src/util/statsmanager.cpp:54
#5  0x00000000005d595c in StatsManager::run (this=0xc946b0) at src/util/statsmanager.cpp:63
#6  0x00007ffff730dfcb in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007ffff215ee9a in start_thread (arg=0x7fffdd42c700) at pthread_create.c:308
#8  0x00007ffff0949cbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#9  0x0000000000000000 in ?? ()

I'll see if I can reproduce in stock 1.11 branch

**Comment by Holzhaus** [comment]
(by rryan)
I'm pretty sure I fixed this. Re-open if you see it again?
