### ISSUE TITLE
intel i965 driver segfault when closing wspinny

### ISSUE THREAD

**Issue by Holzhaus** [Holzhaus/mixxx-gh-issue-migration#92]
Hi everyone,
I compiled latest Mixxx trunk (r3301) and I got a segfault when I close spinning vinyl. To reproduce:

- launch Mixxx;
- select any GL waveform rendering mode;
- open a spinning vinyl;
- close the opened spinning vinyl.

OS: Xubuntu 11.10 64bit;
CPU: Pentium(R) Dual-Core  CPU      E5700  @ 3.00GHz
Video: Integrated Graphics Chipset: Intel(R) G41

From dmesg:
mixxx[8514]: segfault at 1665c ip 00007f028462d294 sp 00007fff0f85cbe0 error 4 in i965_dri.so[7f02845fb000+b5000]

I attach the gdb output.

**Comment by Holzhaus** [comment]
(by francesco-minchiatti)

**Comment by Holzhaus** [comment]
(by rryan)
Hi Francesco,

Thanks for the backtrace! The segfault is in your Intel graphics drivers. It could be we are using OpenGL wrong but I'm inclined to guess this is just a bug in the Intel graphics drivers. Can you try Xubuntu 12.04 to see if that improves things?

**Comment by Holzhaus** [comment]
(by francesco-minchiatti)
I recompiled r3301 trunk on Xubuntu 12.04.1 live 64bit, (I didn't upgraded the distro before, just installed required packages for building), and I wasn't able to crash it. So you should be right ;-)

**Comment by Holzhaus** [comment]
(by daschuer)
I have committed some patches, solving white widgets with Intel driver on Ubuntu Lucid. Bug #981210, Bug #1089672 . 
Maybe they solve luckily this bug as well. 
Can you please retest our current Mixxx 1.11 beta 2. 

Here the relevant part of your back trace for info: 

Thread 1 (Thread 0x7ffff7fb67a0 (LWP 14387)):
#0  0x00007fffd6845294 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
---Type <return> to continue, or q <return> to quit---
#1  0x00007ffff3065422 in ?? () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#2  0x00007ffff63904c5 in QGLContext::swapBuffers() const ()
   from /usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4
#3  0x00000000006334f2 in QtWaveformWidget::postRender (this=0x1f43970)

**Comment by Holzhaus** [comment]
(by daschuer)
I can see no segfault when switching spinny, but I see white areas. 
It seams that the waveform is painted one time with the wrong old size before it is shown correctly. 
This might be an other causes for the segfault with intel.

**Comment by Holzhaus** [comment]
(by francesco-minchiatti)
I wasn't able to crash the r3640, so the issue should be fixed.
I confirm that a white flash is shown in place of spinny when switching a spinny itself, but is too fast to appreciate other details.

**Comment by Holzhaus** [comment]
(by daschuer)
I have filled a separate Bug for the white area issue: Bug #1100883. 

Since you are not able to reproduce the crash with recent versions, I think it is save to close this on.
